name: ci-golang-workflow
on: [push]
jobs:
  check-application:
    runs-on: ubuntu-latest
    stpes:
      - uses: actions/checkout@v2
      - uses: actions/steup-go@v2
        with:
          go-version: 1.15
      - run: go test
      - run: go run math.go
